Components
eamador1/bookstore-redux pull request #1
Opened 2023-09-29 18:08 UTC by eamador1

In this project, the following has been done:
---

- Setup a new React application using [Create React App]
- Create a directory for your reusable components: /components.
- Install [React Router V6]
- [Setup your router] inside of <App>
- Add 2 routes in your application, each should render a page component:
1. /
2. /categories

- Create components inside of the /components directory:
1. Contains individual book state, as well as a button to delete the book
2. Contains a list to renders individual books
3. Contains a form to create new books
4. Contains a navigation to link to the 2 routes you created

2023-09-29 20:05 UTC, zieeco requested changes
Hi @eamador1,



<img height="200" src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>



Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Great effort initializing the bookstore using create react app.✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._



## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-29 20:05 UTC, zieeco commented on README.md
> +
- Hey, the link to the license is currently broken, please, kindly fix this to ensure the link works as expected to make your readme more professional.

2023-09-29 20:05 UTC, zieeco commented on README.md
> +
- Please, kindly fix the typo on the bookstore to make your readme more professional.

2023-09-29 20:05 UTC, zieeco commented on src/App.js
> +      </section>
**[OPTIONAL]**

- To enforce good use of the semantic tags, this section should be a header tag instead as the header contains the logo and the nav items as this is semantically correct following this to improve your semantic usage. kindly fix this :+1:

2023-09-29 20:05 UTC, zieeco commented on README.md
> +```
- Please, let's ensure we've made the correct reference to the current project which is the bookstore as the instruction here leads to a different project. Please, fix this to ensure your readme has the correct content relevant to your current project to make your readme more professional. :+1:

2023-09-29 20:05 UTC, zieeco commented on src/App.js
> +        <Route path="categories" element={<Categories />} />
- Hey, let's improve on your links to make them visually appealing to the user.
  - You've added two links to the books and categories but only the categories are currently showing up as you've not explicitly linked to the books route as you ought to. To fix this, add a `/` to the categories path 
  `path="/categories"`, that way the route knows the default or main route is the books, and the categories are another relative link after the books.

2023-09-29 20:05 UTC, zieeco commented on src/App.css
>      animation: App-logo-spin infinite 20s linear;
- Hey, let's remove the dummy style rule we've added from the create react app, as you're not using them in this app to keep your codebase clean and better to maintain.

2023-09-29 20:05 UTC, zieeco commented on src/App.js
> +          <NavLink to="categories" className={({ isActive }) => isActive && activeClassName}>Categories</NavLink>
- To improve the user experience on the active links, let's make some changes to your code to achieve that result as you're not using the react activeclassname correctly. here's how to do it correctly. follow the steps below:

   - when trying to make each link active, you can use the react activeclassname attribute which needs you to have a CSS class of `active` so when it sees the class, it can add the style to it. you should update your code like this below 
   
```
<NavLink to="" activeclassname="active-link" className>Books</NavLink>
 <NavLink to="categories" activeclassname="active-link">Categories</NavLink>
```
   - Also, kindly delete the `const activeClassName = 'nav-active';` as you don't need it anymore.
   - you can do a little CSS reset to your li, ul, and a tag
   
   ```
ul,
li,
a {
  list-style: none;
  text-decoration: none;
  color: inherit;
}
```

   - Then, finally, add the class of active. you do not need to add the `active` to any element as the `activeclassname="active-link"` expect to see a class with the name `active` then apply the style to the links:
   
   ```
.active {
  color: #0290ff;
  text-decoration: underline;
}
```

- Your link should work correctly now.

![image](https://github.com/eamador1/bookstore-redux/assets/59397159/3dea30f9-ddb4-4a13-8c40-677000c738e6)
![image](https://github.com/eamador1/bookstore-redux/assets/59397159/fde44a83-2e26-46da-aaf2-74dc598e7d34)

2023-09-29 21:03 UTC, eamador1 commented
@zieeco Absolutely awesome. Thank you very much for this review. It helped a lot and I will not make those mistakes again.

2023-09-30 01:52 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-02 17:50 UTC, merged