Styling
eamador1/bookstore-redux pull request #5
Opened 2023-10-08 03:36 UTC by eamador1

Since the last code review, the following was done in this project:
---

- Add any missing JSX elements to project (without adding extra functionality) ✅
- final design match Zeplin's design (this includes all elements + the same styling) ✅
- Use the CSS rules detailed in Zeplin to style the website ✅

2023-10-08 04:38 UTC, shahadat3669 requested changes
Hi @eamador1, 

Great job so far! 👏 You've done well, and you're almost there for the next project ⏭️, but there are a few issues 🐛 that you still need to work on.

<img  src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif" />


## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ No linter Errors
✅ No repeated id or class
✅ The code is top-notch! 💯


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-08 04:38 UTC, shahadat3669 commented on src/App.js
>          </nav>
- [ ] Your navbar component is a great addition to your app; however, it currently doesn't align with the provided design. To enhance your app's aesthetics and user experience, please ensure that you use the specified layout to match the design. Please ensure that the navbar is full with the book's card. By incorporating these design elements, you'll bring your navbar closer to the intended design, improving the overall look and feel of your app. Keep up the good work! 👍🎨

| Your | Design |
| --- | --- |
|![image](https://github.com/eamador1/bookstore-redux/assets/55840999/b2d3cf0e-a975-4f02-b700-1092fcbf8b75)|  ![image](https://github.com/eamador1/bookstore-redux/assets/55840999/64a3fa05-b200-4517-841d-2a828132c1a6)|

2023-10-08 04:38 UTC, shahadat3669 commented on src/components/Form.jsx
>      </form>
- [ ] 👍 Good work so far! However, there's a minor layout issue. As per the design, your input fields should take up the full width until the button, and the button should be aligned horizontally with the card on the right side. Currently, they are not aligned as intended. Please update your code to ensure that the layout matches the design, providing a more polished and visually consistent appearance. Keep it up! 🛠️👏🎨

| Your | Design |
| --- | --- |
|  ![image](https://github.com/eamador1/bookstore-redux/assets/55840999/e12096ba-da3a-40f0-8db9-0669ab3fab69)| ![image](https://github.com/eamador1/bookstore-redux/assets/55840999/e8ac791c-3425-4dc6-9d30-96f4dac85cf6)|

2023-10-08 04:38 UTC, shahadat3669 commented on src/components/Book.jsx
> +            </div>
- [ ] It looks good that you added a circular progress bar, but it is smaller compared to the design. Please consider updating it.

| Your | Design |
| --- | --- |
|  ![image](https://github.com/eamador1/bookstore-redux/assets/55840999/4787d3d1-2c23-4002-a1a6-cbd521168b9a)| ![image](https://github.com/eamador1/bookstore-redux/assets/55840999/b60d0723-ec24-4302-83ad-b7dc6583237a)|

2023-10-08 04:38 UTC, shahadat3669 commented on src/components/Book.jsx
> +        </div>
👍 Good job with the layout! However, there are a couple of improvements needed to match the design precisely:

- [ ] Firstly, as per the design, there should be no horizontal line after the last button, which is the 'Edit' button. Please update your code to remove the line after the 'Edit' button, aligning it with the design.

- [ ] Secondly, the horizontal lines should be evenly spaced between the buttons. Currently, they are not evenly spaced. Please adjust your code to ensure that the horizontal lines are evenly distributed between each button, adhering to the design specifications.

| Your | Design |
| --- | --- |
|  ![image](https://github.com/eamador1/bookstore-redux/assets/55840999/03227746-a584-464b-b0fb-5e9777ce0f7b)| ![image](https://github.com/eamador1/bookstore-redux/assets/55840999/d1ae7e84-7bda-4bc6-af6a-d0404077348c)|

These adjustments will help your layout closely match the design, enhancing its visual consistency. Great work, and keep refining the details! 🎨👍✨

2023-10-08 04:38 UTC, shahadat3669 commented on src/App.js
👍 Great work on the components! However, to align them more closely with the design, consider the following improvements:

- [ ] Wrap all components within an outer wrapper element. This wrapper should have a shadow effect to match the design's visual style. Incorporating a shadow will provide a more polished and professional appearance. Pay attention to the spacing and layout, ensuring that elements are properly aligned and spaced as per the design specifications. You can refer to this [example](https://pedantic-beaver-cb923b.netlify.app/#/) to understand the desired layout.


| Your | Design |
| --- | --- |
|  ![image](https://github.com/eamador1/bookstore-redux/assets/55840999/8ba7bc4a-e6c2-4dc5-8704-59da34ad9b73)| ![Bookstore CMS (1)](https://github.com/eamador1/bookstore-redux/assets/55840999/3ce0efa9-9009-430c-afb3-5c96bd5752ca)|


By adding the outer wrapper with a shadow and fine-tuning the spacing, your components will closely match the design, creating a more visually appealing and consistent user interface. Keep up the excellent work! 🎨👍✨

2023-10-08 06:03 UTC, eamador1 commented
Since the last code review, the following changes were made:
---
-wrap all components
-fix vertical lines in button
-circular bar has same width and height as example
-align all components

2023-10-08 06:16 UTC, mukhammadrizooff requested changes
Hi @eamador1, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-08 06:16 UTC, mukhammadrizooff commented on src/App.css
- [ ] [REQUIRED] Good job so far! As previous reviewer mentioned about your main box of project should be give `shadow` property and pay attention to `distance of elements from the border of box, in your project I see these aspects are not fixed yet. Please improve them 🙏🏼 

![image](https://github.com/eamador1/bookstore-redux/assets/63915024/03e568a4-4d5a-4beb-abea-3d6a53e5a37c)
  
![image](https://github.com/eamador1/bookstore-redux/assets/63915024/12fecb0d-f5d5-4318-8cfe-de5c97260899)

2023-10-09 20:04 UTC, eamador1 commented
Since the last code review, the following was done:
---

- import react-circular-progressbar library ✅
- give shadow property to books container ✅
- give proper distance to elements in app ✅

2023-10-09 20:41 UTC, ShadyShawkat approved these changes
## Hi @eamador1, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 
- Your readme looks professional ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-11 20:34 UTC, merged